services:
  app:
    restart: unless-stopped
    container_name: institucional-8ksoft
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8530:8530"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ["npm", "start"]
